name: CI/CD - API Gateway

on:
  push:
    paths:
      - "api-gateway/**"

jobs:
  api-gateway-pipeline:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Build
      run: mvn -pl api-gateway -am clean package

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build & Push Image
      run: |
        docker build -t deepika1308/hotel-api-gateway:${{ github.sha }} ./api-gateway
        docker push deepika1308/hotel-api-gateway:${{ github.sha }}

    - name: Deploy
      run: |
        kubectl set image deployment/api-gateway \
        api-gateway=deepika1308/hotel-api-gateway:${{ github.sha }} \
        -n hotel-ms
