name: CI/CD - Booking Service

on:
  push:
    paths:
      - "booking-service/**"

jobs:
  booking-service-pipeline:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Build & Test
      run: mvn -pl booking-service -am clean package

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build & Push Image
      run: |
        docker build -t deepika1308/hotel-booking-service:${{ github.sha }} ./booking-service
        docker push deepika1308/hotel-booking-service:${{ github.sha }}

    - name: Deploy
      run: |
        kubectl set image deployment/booking-service \
        booking-service=deepika1308/hotel-booking-service:${{ github.sha }} \
        -n hotel-ms
