#rejoin
name: CI/CD - Eureka Server

on:
  push:
    paths:
      - "eureka-server/**"
  workflow_dispatch:

jobs:
  eureka-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Eureka Server (Skip Tests)
        run: mvn -pl eureka-server -am clean package -DskipTests

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build & Push Docker Image
        run: |
          docker build -t deepika1308/hotel-eureka-server:${{ github.sha }} ./eureka-server
          docker push deepika1308/hotel-eureka-server:${{ github.sha }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/eureka-server \
          eureka-server=deepika1308/hotel-eureka-server:${{ github.sha }} \
          -n hotel-ms
