name: CI/CD - Eureka Server

on:
  push:
    paths:
      - "eureka-server/**"

jobs:
  eureka-pipeline:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Build
      run: mvn -pl eureka-server -am clean package

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build & Push Image
      run: |
        docker build -t deepika1308/hotel-eureka-server:${{ github.sha }} ./eureka-server
        docker push deepika1308/hotel-eureka-server:${{ github.sha }}

    - name: Deploy
      run: |
        kubectl set image deployment/eureka-server \
        eureka-server=deepika1308/hotel-eureka-server:${{ github.sha }} \
        -n hotel-ms
