name: CI/CD - Hotel Service

on:
  push:
    paths:
      - "hotel-service/**"

jobs:
  hotel-service-pipeline:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Build & Test
      run: mvn -pl hotel-service -am clean package

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build & Push Image
      run: |
        docker build -t deepika1308/hotel-hotel-service:${{ github.sha }} ./hotel-service
        docker push deepika1308/hotel-hotel-service:${{ github.sha }}

    - name: Deploy
      run: |
        kubectl set image deployment/hotel-service \
        hotel-service=deepika1308/hotel-hotel-service:${{ github.sha }} \
        -n hotel-ms
